version: "3.3"
services:
  marktplaatsscraper:
    build: .
    volumes:
      - /config:/CONFIG_DIR
    environment:
      PUSHOVER_API_TOKEN: TOKEN
      PUSHOVER_USER: USER
      SCANNING_INTERVAL: 120
