#!/usr/bin/with-contenv sh

# Check if this is the first time running the container
apk update
apk info -vv | grep 'python3'
if [[ $? -eq 1 ]]; then # It is running for the first time! Let's install things..
  # Update repo's!
  echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" > /etc/apk/repositories
  echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

  # Update APK
  apk update

  # Install git
  apk add git tar

  # Install Chromium + Webdriver
  apk add chromium
  apk add chromium-chromedriver

  # Install Python and selenium
  apk add python3
  apk add py3-pip
  echo python3 -v

  pip3 install wheel

  # Download MarktplaatsScraper and install requirements
  git clone https://github.com/JasperMC/MarktplaatsScraper.git
  cp -u -R MarktplaatsScraper/* /config
  rm -rf MarktplaatsScraper
  cd /config
  #pip3 install -r requirements.txt
  pip3 install python-pushover
  #pip3 install selenium
  #pip install python-pushover
  #pip install selenium
  pip3 list
  pip3 list | grep 'python-pushover'
  if [[ $? -eq 1 ]]; then
    
    echo "Python Pushover is installed!"
    echo python -v
    echo python3 -v
  fi
fi
  
exit 0
